INSERT INTO "instruments" VALUES(1,'ACS',NULL);
INSERT INTO "instruments" VALUES(2,'NICMOS',NULL);
INSERT INTO "instruments" VALUES(3,'WFPC2',NULL);
INSERT INTO "instruments" VALUES(4,'WFC3',NULL);
INSERT INTO "instruments" VALUES(5,'2MASS',NULL);
INSERT INTO "instruments" VALUES(6,'WISE',NULL);
