INSERT INTO "spectral_types" VALUES(1,1,20.0,'','III','','',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "spectral_types" VALUES(2,2,42.0,'','V',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "spectral_types" VALUES(3,3,64.0,NULL,'V',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "spectral_types" VALUES(4,4,51.0,NULL,'V-IV',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
